name: Minipod Build & Test

on:
  workflow_call:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Install
      run: sudo make -C ${{github.workspace}}/build install

    - name: Run tests
      run: make -C ${{github.workspace}}/test
