name: Build

on:
  workflow_call:
  push:
    branches: [ zig ]
  pull_request:
    branches: [ zig ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: mlugg/setup-zig@v2
    - run: zig build
