name: Minipod Build & Test

on:
  workflow_call:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Install
      run: sudo make -C ${{github.workspace}}/build install

    - name: Configure CMake for tests
      run: cmake -DBUILD_TESTS=true -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test checks
      run: ${{github.workspace}}/build/test/test-checks

    - name: Test utils
      run: ${{github.workspace}}/build/test/test-utils

    - name: Test minipod-lib
      run: ${{github.workspace}}/build/test/test-minipod-lib

    - name: Test fine-circular-buffer
      run: ${{github.workspace}}/build/test/test-fine-circular-buffer
